-- MySQL Script generated by MySQL Workbench
-- 07/02/15 16:33:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GaS_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GaS_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GaS_database` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `GaS_database` ;

-- -----------------------------------------------------
-- Table `GaS_database`.`Pittori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GaS_database`.`Pittori` (
  `idPittori` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Descrizione` TEXT(3000) NULL,
  `AutoreDescrizione` VARCHAR(45) NULL,
  `Foto` VARCHAR(45) NOT NULL,
  `Indirizzo` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Mail` VARCHAR(45) NULL,
  `Facebook` VARCHAR(100) NULL,
  `Twitter` VARCHAR(45) NULL,
  `Google+` VARCHAR(100) NULL,
  PRIMARY KEY (`idPittori`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GaS_database`.`Quadri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GaS_database`.`Quadri` (
  `idQuadri` INT NOT NULL AUTO_INCREMENT,
  `Titolo` VARCHAR(45) NOT NULL,
  `NumeroPosti` INT NOT NULL,
  `Descrizione` TEXT(3000) NULL,
  `Immagine` VARCHAR(45) NOT NULL,
  `Recente` TINYINT(1) NOT NULL,
  `Pittori_idPittori` INT NOT NULL,
  PRIMARY KEY (`idQuadri`, `Pittori_idPittori`),
  INDEX `fk_Quadri_Artisti_idx` (`Pittori_idPittori` ASC),
  CONSTRAINT `fk_Quadri_Artisti`
    FOREIGN KEY (`Pittori_idPittori`)
    REFERENCES `GaS_database`.`Pittori` (`idPittori`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GaS_database`.`Carosello`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GaS_database`.`Carosello` (
  `idCarosello` INT NOT NULL AUTO_INCREMENT,
  `Immagine` VARCHAR(45) NULL,
  PRIMARY KEY (`idCarosello`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GaS_database`.`Gruppo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GaS_database`.`Gruppo` (
  `idGruppo` INT NOT NULL AUTO_INCREMENT,
  `Foto` VARCHAR(45) NOT NULL,
  `Descrizione` TEXT(3000) NOT NULL,
  `Indirizzo` VARCHAR(45) NULL,
  `NumeroTel` VARCHAR(45) NULL,
  `Mail` VARCHAR(45) NULL,
  PRIMARY KEY (`idGruppo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GaS_database`.`Eventi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GaS_database`.`Eventi` (
  `idEventi` INT NOT NULL AUTO_INCREMENT,
  `Titolo` VARCHAR(45) NOT NULL,
  `Descrizione` TEXT(3000) NOT NULL,
  `Luogo` VARCHAR(45) NULL,
  `DataInizio` DATE NOT NULL,
  `DataFine` DATE NULL,
  `Immagine` VARCHAR(45) NULL,
  PRIMARY KEY (`idEventi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GaS_database`.`Pittori_has_Eventi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GaS_database`.`Pittori_has_Eventi` (
  `Pittori_idPittori` INT NOT NULL,
  `Eventi_idEventi` INT NOT NULL,
  PRIMARY KEY (`Pittori_idPittori`, `Eventi_idEventi`),
  INDEX `fk_Artisti_has_Eventi_Eventi1_idx` (`Eventi_idEventi` ASC),
  INDEX `fk_Artisti_has_Eventi_Artisti1_idx` (`Pittori_idPittori` ASC),
  CONSTRAINT `fk_Artisti_has_Eventi_Artisti1`
    FOREIGN KEY (`Pittori_idPittori`)
    REFERENCES `GaS_database`.`Pittori` (`idPittori`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artisti_has_Eventi_Eventi1`
    FOREIGN KEY (`Eventi_idEventi`)
    REFERENCES `GaS_database`.`Eventi` (`idEventi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GaS_database`.`Eventi_has_Quadri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GaS_database`.`Eventi_has_Quadri` (
  `Eventi_idEventi` INT NOT NULL,
  `Quadri_idQuadri` INT NOT NULL,
  PRIMARY KEY (`Eventi_idEventi`, `Quadri_idQuadri`),
  INDEX `fk_Eventi_has_Quadri_Quadri1_idx` (`Quadri_idQuadri` ASC),
  INDEX `fk_Eventi_has_Quadri_Eventi1_idx` (`Eventi_idEventi` ASC),
  CONSTRAINT `fk_Eventi_has_Quadri_Eventi1`
    FOREIGN KEY (`Eventi_idEventi`)
    REFERENCES `GaS_database`.`Eventi` (`idEventi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Eventi_has_Quadri_Quadri1`
    FOREIGN KEY (`Quadri_idQuadri`)
    REFERENCES `GaS_database`.`Quadri` (`idQuadri`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
